image: gitlab.laas.fr:4567/gsaurel/talks

build:
  stage: build
  script:
    - make all
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  only:
    refs:
      - main@gsaurel/talks
  variables:
    GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=.known_hosts"
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - git config --global --add safe.directory /builds/gsaurel/talks
    - git fetch
    - git checkout main
    - git pull origin main
  script:
    - make deploy
    - git push git@github.com:nim65s/talks main
